// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhZ2EhpnFUKGGHIvzDtxNVsRSt_qJJklU',
    appId: '1:707904572567:web:90292be7edffbfda6eadd2',
    messagingSenderId: '707904572567',
    projectId: 'quick-commerce-4f3e6',
    authDomain: 'quick-commerce-4f3e6.firebaseapp.com',
    storageBucket: 'quick-commerce-4f3e6.firebasestorage.app',
    measurementId: 'G-JH2GYPSSMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMBpbD7VqXzw8t3MV1Cgfs7NO67EL4RuI',
    appId: '1:707904572567:android:c2cbcc618b489b736eadd2',
    messagingSenderId: '707904572567',
    projectId: 'quick-commerce-4f3e6',
    storageBucket: 'quick-commerce-4f3e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ek0wk1jZJdC3C02NhcmlPzkOG9ytEf4',
    appId: '1:707904572567:ios:0cee6000e7996c116eadd2',
    messagingSenderId: '707904572567',
    projectId: 'quick-commerce-4f3e6',
    storageBucket: 'quick-commerce-4f3e6.firebasestorage.app',
    iosBundleId: 'com.example.quickCommerceApp',
  );
}
